Load(graph);
Import(graph);
opts := SparseDefaults;
opts.useDeref := false;
opts.globalUnrolling := 0;
n := var.fresh_t("n", TInt);
opts.symbol := [n];
ts := TSparse(TArray(TInt, 5), TSemiring_Arithmetic(TInt));
fdos := FDataSparseOfs(ts, 5, 0);
rv := RowVec(fdos);
i := Ind(5);
ivs := IterVStack(i, 5, rv);
rt := RandomRuleTree(last, opts);
srt := SumsRuleTree(rt, opts);
cs := CodeSums(srt, opts);
PrintCode("spmv", cs, opts);